import StyleDictionary from 'style-dictionary';
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

/**
 * @travl/tokens build
 *
 * Input:  tokens/*.json  (DTCG, exported from Figma by the Travl Token Export plugin)
 * Output: dist/css/light.css      :root scope
 *         dist/css/dark.css       [data-theme="dark"] scope
 *         dist/css/index.css      both themes in one file
 *         dist/tailwind/theme.css Tailwind v4 @theme mapping
 *
 * Architecture rule enforced here: primitives participate in alias
 * resolution but are filtered out of every artifact. Only semantic
 * tokens ship as public CSS variables.
 */

const semanticOnly = (token) => !token.filePath.includes('primitives');

// Non-color primitives that have no semantic layer yet but are part of
// the public contract (type roles, motion, breakpoints). These are
// role-named already, so they ship alongside the semantic tokens.
const publicPrimitivePrefixes = ['font', 'duration', 'ease', 'breakpoint'];
const publicApi = (token) =>
  semanticOnly(token) || publicPrimitivePrefixes.includes(token.path[0]);

const themes = [
  {
    name: 'light',
    selector: ':root',
    sets: ['tokens/primitives.json', 'tokens/semantic.light.json'],
  },
  {
    name: 'dark',
    selector: '[data-theme="dark"]',
    sets: ['tokens/primitives.json', 'tokens/semantic.dark.json'],
  },
];

// --- Tailwind v4 @theme format --------------------------------------------
// Emits an `@theme inline` block that maps Tailwind namespaces onto the
// runtime CSS variables produced by the css/variables format. `inline`
// makes utilities reference the variable at use-time, so dark mode
// resolves through [data-theme="dark"] with no extra Tailwind config.
//
// Breakpoints are the one exception and get their own NON-inline block.
// Tailwind expands `--breakpoint-*` into `@media (width >= …)`, and a media
// query cannot read a custom property — emitting them inline produces
// `@media (width >= var(--breakpoint-lg))`, which is invalid CSS and hard-
// fails any minifier that validates media queries. Breakpoints are also
// mode-invariant, so nothing is lost by baking in the literal.
StyleDictionary.registerFormat({
  name: 'tailwind/theme',
  format: ({ dictionary }) => {
    const inlineLines = [];
    const staticLines = [];
    for (const token of dictionary.allTokens) {
      const name = token.path.join('-');
      const ns = token.path[0];

      if (ns === 'breakpoint') {
        staticLines.push(`  --${name}: ${token.$value ?? token.value};`);
        continue;
      }

      let themeVar = null;
      if (ns === 'color') themeVar = `--${name}`; // --color-*
      else if (ns === 'space') themeVar = `--spacing-${token.path.slice(1).join('-')}`;
      else if (ns === 'radius') themeVar = `--${name}`; // --radius-*
      else if (ns === 'font') themeVar = `--${name}`; // --font-*
      else if (ns === 'ease') themeVar = `--${name}`; // --ease-*
      else if (ns === 'text') {
        // Type roles are 5-part composites (text/body/md/{family,size,...}).
        // Tailwind's --text-* namespace is font-size only, so only the `size`
        // leaf becomes a utility: text-body-md. The other four leaves stay
        // available as raw variables for the component tier.
        if (token.path.at(-1) !== 'size') continue;
        themeVar = `--text-${token.path.slice(1, -1).join('-')}`;
      }
      if (themeVar) inlineLines.push(`  ${themeVar}: var(--${name});`);
    }
    return [
      '/* Generated by @travl/tokens — do not edit. */',
      '/* Import after dist/css/index.css so the runtime variables exist. */',
      '@theme inline {',
      ...inlineLines,
      '}',
      '',
      '/* Literal values: Tailwind inlines these into media queries, which',
      '   cannot dereference a custom property. */',
      '@theme {',
      ...staticLines,
      '}',
      '',
    ].join('\n');
  },
});

// --- Build -----------------------------------------------------------------

for (const theme of themes) {
  const sd = new StyleDictionary({
    source: theme.sets,
    platforms: {
      css: {
        transformGroup: 'css',
        buildPath: 'dist/css/',
        files: [
          {
            destination: `${theme.name}.css`,
            format: 'css/variables',
            options: { selector: theme.selector },
            filter: publicApi,
          },
        ],
      },
      ...(theme.name === 'light' && {
        tailwind: {
          transformGroup: 'css',
          buildPath: 'dist/tailwind/',
          files: [
            {
              destination: 'theme.css',
              format: 'tailwind/theme',
              filter: publicApi,
            },
          ],
        },
      }),
    },
  });
  await sd.buildAllPlatforms();
}

// Combined stylesheet: light defaults + dark override in one import.
mkdirSync('dist/css', { recursive: true });
writeFileSync(
  'dist/css/index.css',
  readFileSync('dist/css/light.css', 'utf8') +
    '\n' +
    readFileSync('dist/css/dark.css', 'utf8'),
);

console.log('✔ @travl/tokens built: dist/css/{light,dark,index}.css + dist/tailwind/theme.css');
